version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_assignment5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: DhruvPass!9062297
      MYSQL_DATABASE: assignment5
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data:/data
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mysql_data:
